# Examen 1


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# Pregunta 1
x = np.arange(10)




In [ ]:
# Pregunta 2
seg = x[4:8]
print(seg)
#Aqui llamamos seg a la segmentación de los valores de x, siendo del 4 al 7, con el print obtenemos lo que queremos.

[4 5 6 7]


In [ ]:
# Pregunta 3
x1, x2, x3 = np.split(x, [3,6])
print(x1)
print(x2)
print(x3)
# El x1 da los primeros tres numeros, el x2 da los siguientes tres numeros, y el x3 da los ultimos 4 numeros.

[0 1 2]
[3 4 5]
[6 7 8 9]


In [ ]:
# Pregunta 4
data = pd.DataFrame({'Country':['Russia', 'Colombia', 'Chile', 'Equador', 'Nigeria'],'Rank':[121, 40, 100, 130, 11]})


In [ ]:
# Pregunta 5
data.info()
# Los valores que se muestran con la función info del data frame anterior es información sobre el mismo. En este caso nos señala que hay 5 valores para Country como para Rank,
#lo cual se divide en 2 columnas("Country" y "Rank")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Country  5 non-null      object
 1   Rank     5 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 208.0+ bytes


In [ ]:
# Pregunta 6
data_2 = pd.DataFrame({'k1':['one']*3 + ['two']*4, 'k2':[3,2,1,3,3,4,4]})
# a) Se esta creando un diccionario de dos columnas, en los valores de las llaves se le estan dando atributos a k1 y a K2.
# Donde para k1 se repetira la palabra one tres veces y la palabra two cuatro veces. Y para k2 se daran los valores que aparecen entre corchetes.

In [ ]:
# Pregunta 6b
print(data_2)
# con la función print(data_2) obtenemos el dicciónario antes explicado.

    k1  k2
0  one   3
1  one   2
2  one   1
3  two   3
4  two   3
5  two   4
6  two   4


In [ ]:
# Pregunta 7
# El atributo drop_duplicate() sirve para quitar filas que se encuentren mas de una vez dentro de un dataframe o diccionario, para así quedarse con una sola fila con esos valores.

In [ ]:
# Pregunta 8
data_3 = pd.DataFrame(np.arange(12).reshape((3, 4)),index=['CDMX', 'Guanajuato', 'Puebla'],columns=['uno', 'dos', 'tres', 'cuatro'])
print(data_3)
# Data_3 es un dataframe obtenido con pandas con distintos valores. Primero el np.arrange(12) nos da valores del 0 al 11. Con el reshape(3,4) se nos dice que la tabla o matriz sera de 3x4.
# El index nos da los nombres que apareceran en la filas (3), mientras que columns nos da los nombres de las columnas (4)

            uno  dos  tres  cuatro
CDMX          0    1     2       3
Guanajuato    4    5     6       7
Puebla        8    9    10      11


In [ ]:
# Pregunta 9
data_3.rename(index={'CDMX':'Monterrey', 'Guanajuato':'Guadalajara', 'Puebla': 'Cholula'})
# Con la función rename, renombramos los nombres de las flias, cambiando CDMX por Monterrey, Guanajuato por Guadalajara y Puebla por Cholula

uno  dos  tres  cuatro
Monterrey      0    1     2       3
Guadalajara    4    5     6       7
Cholula        8    9    10      11

In [ ]:
# Pregunta 10
df = pd.DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'], 'key2' : ['one', 'two', 'one', 'two', 'one'], 'data1' : np.random.randn(5),'data2' : np.random.randn(5)})
# El siguiente código es un dataframe obtenido con pandas, el cual tiene dos columnas con valores string ("key1", "key2") y dos columnas con valores numericos usando numpy("data 1", "data 2").
# Las columnas Key 1 y Key 2 arrogaran sus valores que tienen, mientras que data 1 y data 2 arrogaran numeros aleatorios gracias a la funcion random.randn
print(df)

  key1 key2     data1     data2
0    a  one  0.445131  0.243876
1    a  two -0.423257 -0.488980
2    b  one  0.288721 -0.728526
3    b  two  0.874279 -0.725258
4    a  one -0.413663  1.682805


In [ ]:
# Pregunta 10 continuación
# a) A continuación quitaremos la columna key 2 con la función drop.

df = pd.DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'], 'key2' : ['one', 'two', 'one', 'two', 'one'], 'data1' : np.random.randn(5),'data2' : np.random.randn(5)})
df = df.drop(columns='key2')

print(df)


  key1     data1     data2
0    a  0.332141 -0.078546
1    a -0.678773 -0.505873
2    b -0.560453  0.600250
3    b  1.382500  0.170237
4    a  0.424952  1.088343


In [ ]:
#Pregunta 10 b
# Con la función set_index cambiamos key al indice
df = pd.DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'], 'key2' : ['one', 'two', 'one', 'two', 'one'], 'data1' : np.random.randn(5),'data2' : np.random.randn(5)})
df=df.set_index('key1')
print(df)

     key2     data1     data2
key1                         
a     one  0.250139 -0.688260
a     two  0.593564 -2.319582
b     one -0.555723  0.593508
b     two -1.126452  0.105278
a     one  0.445142 -0.037802


In [ ]:
# Pregunta 10c
#Con la funcón describe() nos describe diferentes datos que arroga el data frame.
descripcion = df.describe()
print(descripcion)

          data1     data2
count  5.000000  5.000000
mean  -0.078666 -0.469372
std    0.734816  1.131081
min   -1.126452 -2.319582
25%   -0.555723 -0.688260
50%    0.250139 -0.037802
75%    0.445142  0.105278
max    0.593564  0.593508


In [ ]:
# Pregunta 10 d
#Con la función mean se nos da la media de las columnas sobrantes del dataframe
med = df.mean()
print(med)

data1   -0.078666
data2   -0.469372
dtype: float64


<ipython-input-98-3ba1654da973>:3: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  med = df.mean()
